import { prepareSvg } from "@/utils/svg-helpers";

// ─── Types ────────────────────────────────────────────────────────────────────

export interface StackNode {
  id: string;
  content: string;
  fillcolor?: string;
  strokecolor?: string;
  textcolor?: string;
  x?: string;
  y?: string;
}

export interface StackData {
  comp_id: string;
  caption?: string;
  nodes?: StackNode[];
  svg_string?: string;
  version?: string;
}

// ─── Component ────────────────────────────────────────────────────────────────

export default function Stack({ data }: { data: StackData }) {
  // Primary rendering: inline SVG generated by the platform
  if (data.svg_string) {
    return (
      <div className="max-w-6xl mx-auto px-6 py-4">
        <div className="flex flex-col items-center gap-3">
          <div
            className="overflow-auto max-w-full dark:brightness-90 dark:invert dark:hue-rotate-180"
            dangerouslySetInnerHTML={{ __html: prepareSvg(data.svg_string) }}
          />
          {data.caption && (
            <p className="text-sm text-gray-500 dark:text-gray-400 text-center italic">
              {data.caption}
            </p>
          )}
        </div>
      </div>
    );
  }

  // Fallback: render nodes as a visual stack list (bottom-to-top)
  const nodes = data.nodes ?? [];
  return (
    <div className="max-w-6xl mx-auto px-6 py-4">
      <div className="flex flex-col items-center gap-px">
        {nodes.map((node, i) => (
          <div
            key={node.id ?? i}
            className="w-56 text-center py-2 font-mono text-sm border"
            style={{
              backgroundColor: node.fillcolor ?? "#bfefff",
              borderColor: node.strokecolor ?? "#ccc",
              color: node.textcolor ?? "#000000",
            }}
          >
            {node.content}
          </div>
        ))}
        {data.caption && (
          <p className="text-sm text-gray-500 dark:text-gray-400 text-center mt-2 italic">
            {data.caption}
          </p>
        )}
      </div>
    </div>
  );
}
